# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#trigger:
#  - master

#pool:
#  vmImage: windows-latest

jobs:
#  - job: macos_test
#    pool:
#        vmImage: macos-latest
#    steps:
#    - task: npmAuthenticate@0
#      inputs:
#        workingFile: obj/.npmrc
#    - script: |
#        rm -r /Users/runner/work/1/s

  - job: ubuntu_test_1
    pool: Default
#        vmImage: ubuntu-latest
    steps:
 #   - script: |
 #       export VSTS_AGENT_CHANNEL_TIMEOUT=125
    - task: npmAuthenticate@0
      inputs:
        workingFile: obj/.npmrc

#  - job: ubuntu_test_2
#    pool:
#        vmImage: ubuntu-latest
#    steps:
#    - task: npmAuthenticate@0
#      inputs:
#        workingFile: obj/.npmrc
#      condition: eq('false', 'true')

#  - job: ubuntu_test_3
#    pool:
#        vmImage: ubuntu-latest
#    steps:
#    - task: npmAuthenticate@0
#      inputs:
#        workingFile: obj/.npmrc

  # - job: windows_test
  #   pool: #Default
  #       vmImage: windows-latest
  #   steps:
  #   - task: npmAuthenticate@0
  #     inputs:
  #       workingFile: .npmrc
  #   - script: |
  #       rmdir D:\a\1\s
